<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Simple Verification Helper</Description>
    <Authors>Hamfer Team</Authors>
    <Company>Hamfer</Company>
    <Copyright>Copyright © Hamfer</Copyright>

    <PackageId>HamferTeam.LetsVerify</PackageId>
    <PackageTags>letsverify,verification,validation,test</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://hamfer.team/</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HamferTeam.LetsVerify</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" Visible="false" PackagePath="/" />
    <None Include="README.md" Pack="true" Visible="false" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kernel\src\kernel.csproj" />
  </ItemGroup>

</Project>
